{
 "title": "Predictions",
 "time": { "from": "now-15m", "to": "now+5m" },
 "templating": {
  "list": [
   { "name": "Hostname", "query": { "query": "label_values(hostname)" } },
   {
    "name": "Interface",
    "query": {
     "query": "label_values({hostname=\"$Hostname\"},interface_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Interfaces - $Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Interface" },
  {
   "title": "Recieved Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "interface_recv_octets{hostname=\"$Hostname\", interface_name=\"$Interface\"}",
     "legendFormat": "{{interface_name}}"
    },
    {
     "expr": "forecasted_interface_octets{hostname=\"$Hostname\", interface_name=\"$Interface\", direction=\"recv\"}",
     "legendFormat": "{{interface_name}}-predicted"
    }
   ]
  },
  {
   "title": "Sent Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "interface_send_octets{hostname=\"$Hostname\", interface_name=\"$Interface\"}",
     "legendFormat": "{{interface_name}}"
    },
    {
     "expr": "forecasted_interface_octets{hostname=\"$Hostname\", interface_name=\"$Interface\", direction=\"send\"}",
     "legendFormat": "{{interface_name}}-predicted"
    }
   ]
  },
  {
   "title": "Recieved Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "interface_recv_packets{hostname=\"$Hostname\", interface_name=\"$Interface\"}",
     "legendFormat": "{{interface_name}}"
    },
    {
     "expr": "forecasted_interface_packets{hostname=\"$Hostname\", interface_name=\"$Interface\", direction=\"recv\"}",
     "legendFormat": "{{interface_name}}-predicted"
    }
   ]
  },
  {
   "title": "Sent Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "interface_send_packets{hostname=\"$Hostname\", interface_name=\"$Interface\"}",
     "legendFormat": "{{interface_name}}"
    },
    {
     "expr": "forecasted_interface_packets{hostname=\"$Hostname\", interface_name=\"$Interface\", direction=\"send\"}",
     "legendFormat": "{{interface_name}}-predicted"
    }
   ]
  }
 ]
}