{
 "title": "Network Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Hostname", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  { "title": "Host Information - $Hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Hostname" },
  {
   "title": "Push Notifications",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "push_notifications_total{hostname=~\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Recieved Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(interface_recv_packets{hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Interface Sent Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(interface_send_packets{hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "MIP Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mip_seqrec_level{hostname=~\"$Hostname\"}) + count(mip_replicate_level{hostname=~\"$Hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Recieved Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "o/s" } },
   "targets": [
    {
     "expr": "rate(interface_send_octets{hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Interface Recieved Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "o/s" } },
   "targets": [
    {
     "expr": "rate(interface_recv_octets{hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}